services:
  - type: web
    name: gembot-ai-web-control
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node launch-server.js
    envVars:
      - key: PORT
        value: 8000
